mainClass="com.kuleuven.lib.GraphExtractor"
graphPath="/data/graph/graph.json"
srcDir="systems/test_application/src"
jarPath="systems/test_application/target/test-application-1.0.jar"
mvn exec:java -Dexec.mainClass=$mainClass -Dexec.args="$graphPath $srcDir $jarPath"